### ISSUE TITLE
Facebook page

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#10]
Please create a Facebook page.

**Comment by adamniedzielski** [comment]
@jackkinsella Will we have a separate Facebook page for the book?

**Comment by jackkinsella** [comment]
https://www.facebook.com/jackkinsellawrites

**Comment by jackkinsella** [comment]
i.e. it will be one page for all the books, just for me as an author

**Comment by adamniedzielski** [comment]
Nice name! Is the similarity to "Nigella bites" just a coincidence or a planned move? :laughing:

**Comment by jackkinsella** [comment]
No it was just random! I already have the URL facebook.com/jackkinsella for my private profile

**Comment by josephdb** [comment]
@jackkinsella could you give me admin permissions on this page please? That was I can post our ads for the book from there :)

**Comment by jackkinsella** [comment]
done

**Comment by josephdb** [comment]
Thank you!
