### ISSUE TITLE
Configure automatic database backups

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#104]
I somehow forgot to do that :disappointed: https://devcenter.heroku.com/articles/heroku-postgres-backups#scheduling-backups

**Comment by adamniedzielski** [comment]
@jackkinsella Important thing to note for the future: "If you upgrade the database from hobby tier to production tier, the schedule will be lost."

**Comment by jackkinsella** [comment]
The principle of _most_ surpise in action...
