### ISSUE TITLE
Test GenerateFinancialTransactionsReport::FetchBalanceTransactions

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#105]
Service object introduced here https://github.com/jackkinsella/confessions/commit/67b203236b86165b6cf7e19eafcc7427fe8254b1

This one is difficult to test, because it relies on some transactions being present in the Stripe test account. What's more, we don't want to reveal the real bank account details and so far it looks like bank accounts are shared between live and test modes. Waiting for Stripe response.

**Comment by adamniedzielski** [comment]
Stripe support suggested creating a separate Stripe account for testing to have a different "dummy" bank account. @jackkinsella Can you do that?

**Comment by jackkinsella** [comment]
sure - invited you to "confessions-test"
