### ISSUE TITLE
Reduced VAT rates

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#106]
@jackkinsella When implementing the accounting system in Oxbridge Notes we decided to ignore the reduced rates and pay higher taxes for the sake of code simplicity.

We can revisit this decision now when implementing the accounting system in Confessions. If we assume that we still want to use https://vatlayer.com then they return the reduced rates in a quite structured way. They have two potentially matching categories: "books" and "e-books". From the fact that they return both "books" and "e-books" for a single country I reason that "books" and "e-books" are mutually exclusive categories, so we should pay attention only to "e-books". In this case there are four EU countries with reduced rates: France, Italy, Luxembourg and Malta.

The implementation from the code perspective is really easy. What do you think?

**Comment by jackkinsella** [comment]
definitely go ahead with it!
