### ISSUE TITLE
New landing page - suggestions

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#108]
1. In the quiz, when an answer is long you may scroll down a little bit. Then you click "Next", but the scrollbar position stays the same, so you cannot see the beginning of the next question. After clicking next, the page should be scrolled to the top of the quiz.
2. My first action after entering the page was checking if the terminal buttons (right upper corner) work. It would be an awesome touch if they do something.
3. "Buy book" scrolls to testimonials. I believe that it should scroll to the "add to cart" button, so a user can reach it as fast as possible.
4. You don't have any chance to go back to the rest of site other than hitting a back button. I fully understand the reasons for that - limiting distractions. On the other hand, it's quite annoying so I suggest adding a super tiny link at the top of the page saying "Go back to the site".

**Comment by jackkinsella** [comment]
thanks - I addressed three of these points in my last commits
