### ISSUE TITLE
Privacy policy - copy needed

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#13]

**Comment by jackkinsella** [comment]
This bulk of this will be the Oxbridge Notes privacy policy (which I just modified: https://github.com/jackkinsella/OxbridgeNotes/blob/development/app/views/home/privacy_policy.html.erb) minus the parts on 

* Paypal
* Facebook Connect

If Stripe gives us data that we store (such as real name or address), we should mention that in lieu of what we currently have for Paypal. I guess we won't know this part until we implement our accounting features.

**Comment by josephdb** [comment]
Just wanted to check — am I assigned to this or no? Or just not until later on when we know more?

**Comment by jackkinsella** [comment]
sure, why not—that would be helpful!

**Comment by josephdb** [comment]
<h1 class="title"> Privacy Policy for <%= MyConfig["site_name"] %> </h1>

<p>If this isn't clear enough or you require any more information about our privacy policy, please feel free to <%= link_to "contact customer support", contact_us_url %>. </p>

<p>The privacy of our visitors is of importance to us. This privacy policy document outlines the types of personal information received and collected by <%= MyConfig["site_name"] %>, and how it is used.</p>

<h3>Cookies</h3>
<p>Like every other website that has log in / log out functionality, we use cookies to maintain user sessions.</p>

<h3>Log Files and Google Analytics</h3>
<p>Like many other web sites, we make use of log files and Google Analytics. The information inside both includes IP addresses, geographic data, types of browsers, Internet Service Providers (ISP), date/time stamps, referring/exit pages, and number of clicks. We use these primarily to debug our codebase, improve our website's speed, and analyse broad trends as to inform management in making decisions about the business's future strategy. IP addresses and other such information are not linked to any information that is personally identifiable.</p>

<h3>Stripe</h3>
<p> As with most other websites using Stripe or similar services, Stripe automatically provides us with your real name and shipping address. We use this information for mandatory taxation and accounting purposes.</p>

<h3>Remarketing </h3>
<p> We let third party advertising companies track whenever you have visited <%= MyConfig["site_name"] %> **and its affiliated websites**. We also use identifying information (such as your email address) to create custom advertising lists. Both of these sources of information are used to display advertisements to you on other websites, such as Google, Facebook, Twitter, and websites affiliated with the aforementioned.</p> _shall I cut that 'affiliated websites' part or is it still relevant?_

<h3>Conversion Tracking </h3>
<p> We use conversion tracking to track whenever you have completed certain commercially valuable actions on our website, chiefly when you have made a purchase. This conversion information is later used by us to figure out what advertising campaigns were effective in triggering this sale. Conversion tracking is done in association with a third party advertising provider (e.g. Twitter, Facebook, Google), who also have access to the data.</p>

**<h3>Enquiries</h3>
<p>We save all enquires made either via our main contact form or via the queries sent to individual authors. We do this for business analysis, monitoring author responsiveness to consumer requests, and policing transactions that are against our terms of services. </p>** _shall I just cut this, or leave the main contact form part?_

<h3>Debugging</h3>
<p> When there is a technical bug with a user account, our staff are empowered to log in with your account and view your account from that perspective. Your password is not leaked to our staff and is stored in a way impossible for them to read.</p>

<h3>Multi-device tracking</h3>
<p>We use Google Analytics universal User-ID to associate engagement data from different devices and multiple sessions.</p>

**Comment by adamniedzielski** [comment]
@jackkinsella Can you answer these two questions at the end of @josephdb comment? Then I will be able to use this copy in the app.

> Two things to check:
> - Remarketing: shall I cut that 'affiliated websites' part or is it still relevant?
> - Enquiries: shall I cut this, or leave the main contact form part and just cut the author parts?

**Comment by adamniedzielski** [comment]
And what is our "site name"? Your name?

**Comment by jackkinsella** [comment]
sorry, I didn't see the questions. Thanks for reminding me!

1. cut affiliated yep
2. cut authors part too.
3. yep, site name is just Jackkinsella.ie

**Comment by adamniedzielski** [comment]
I did these small changes on my own - you can check them.

**Comment by jackkinsella** [comment]
looks a-ok, thanks!
