### ISSUE TITLE
Mailing list - Mailchimp vs. custom

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#17]
@jackkinsella My suggestion would be to start with Mailchimp list just to capture some email addresses when the books and the platform are not ready yet. Then we may import them to our database and switch to custom mailing which uses additional data which we have about them (for instance try to sell the second book if a customer bought only one).

What do you think about this approach?

**Comment by jackkinsella** [comment]
Sounds great. I'll send you my Mailchimp details in Slack.
