### ISSUE TITLE
Analytics proxy

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#21]
We want to send analytics data to:
- Google Analytics (including Ecommerce tracking)
- Google Adwords conversion tracking
- Facebook conversion tracking
- Twitter conversion tracking

In order to do it with Segment, we would have to purchase Startup plan which costs $99. Some of the above integrations are not available in the lower plans. I'm in two minds here, because Segment is wonderful from the perspective of software development, but the price is high.

@jackkinsella What is your opinion?

**Comment by jackkinsella** [comment]
I would love to try out the technology, but it's price-tag is too high. Given that it's a recurring cost, my back-of-a-napkin calculation shows insufficient savings in engineering time to justify over $1000/year.

But let's think about things in terms of having a distinct tracking/data layer, maybe with a tag manager or our own bare-bones JS API for tracking important occurrences and creating a stable interface.

As regards sending data, I agree we need three of four of the ones you mentioned. I would leave out Google Adwords conversion tracking because we can rely on Adwords to pull in Analytics data. In the past, I separately tracked conversions in Adwords and in Analytics, and I found I was tracking the same thing twice and over-complicating things.

**Comment by adamniedzielski** [comment]
Even though we won't be using a paid version of Segment, I still find their integration docs extremely valuable. See https://segment.com/docs/integrations/facebook-pixel/

**Comment by adamniedzielski** [comment]
#### Twitter

The new recommended way of tracking conversions in Twitter is universal website tag. The only thing which we have to do in the app is append the tag before the closing body tag. The rest of the work has to be performed in the Twitter dashboard where we will define rules based on the URL containing certain string.

In some cases we may also want to pass ```tw_sale_amount``` and ```tw_order_quantity``` which makes the integration a little bit more difficult.

**Comment by adamniedzielski** [comment]
#### Facebook

Facebook has a new solution for tracking - Facebook Pixel (as opposed to Conversion Tracking Pixel) - https://developers.facebook.com/docs/facebook-pixel/api-reference It supports 9 standard events and custom events as well.

**Comment by adamniedzielski** [comment]
@jackkinsella I have some questions regarding tracking with Google Analytics:
1. Do you want to use Ecommerce Tracking or Enhanced Ecommerce Tracking?
2. Do we want to track events such as "purchase' in regular Analytics as well, considering the fact that we already have them in Ecommerce Tracking?
3. Do you want to use Google Remarketing? According to this article https://support.google.com/analytics/answer/2444872 it is possible to enable it in the Google Analytics settings without even touching the code. Then this data should be available to Google Adwords (it's not very clear, but I hope it works like that).

**Comment by adamniedzielski** [comment]
@jackkinsella Can we make the assumption that we don't track users with JavaScript disabled? Twitter and Facebook try to account for this case (tracking images), but Google Analytics doesn't do that in the default snippet. What is more, I want to implement the whole tracking proxy in JavaScript, so in fact no tracking will work without JavaScript. Is that OK?

**Comment by jackkinsella** [comment]
1. Regular Ecommerce tracking is sufficient for a simple shop like this.
2. No, I don't think it's necessary to double up on having "purchase" goals as well. Just Ecommerce tracking is enough.
3. Definitely want to use Google Remarketing–and yes, you are right, we can create it in Analytics (/Adwords) without touching the code.
3A. I would add that we also want to use
* Facebook Remarketing
* Twitter Remarketing

**Comment by jackkinsella** [comment]
let's assume everyone has JS– it is 2016 and we are marketing to a young, tech savvy audience.

**Comment by adamniedzielski** [comment]
Facebook Remarketing works out of the box with the new Facebook Pixel. Twitter Remarketing works out of the box with universal website tag. :smile:
