### ISSUE TITLE
Next level of dependency injection

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#22]
I start to notice some downsides of the dead simple approach to dependency injection which I described here http://blog.sundaycoding.com/blog/2014/11/25/my-take-on-services-in-rails/

I have an idea how to make the next small step, but I need to think about it to refine it.

**Comment by jackkinsella** [comment]
Could you document the basic ideas behind your new approach? Just enough for me to be able to dive in and add models without using an inconsistent methodology.

**Comment by jackkinsella** [comment]
Links to blog articles would suffice.

**Comment by zenry** [comment]
Take a look at https://github.com/dry-rb/dry-container

I think the use of symbols (+register) makes it a little better instead of using the class name as key

**Comment by adamniedzielski** [comment]
@zenry Thanks for your contribution! I've read the README of the gem and I believe that it's not an immediate replacement for what we have now.

Basically, what I implemented could be called a "dependency proxy" while ```dry-container``` is well... a "dependency container" :smile: The difference here is that I build all the services using ```DI```, but ```DI``` does not store the instances of the services.

If I were to switch to ```dry-container``` I would have to register all the services in the initializer of the application. This wouldn't play nicely with Rails code reloading in the development environment.

I'm not comfortable with switching to ```dry-container``` right now, but I will definitely consider it in a next project. Thanks again!

**Comment by adamniedzielski** [comment]
Documented here  66214a7
