### ISSUE TITLE
Distribution format of a book

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#23]
@jackkinsella In what format do you plan to distribute books? Is it only PDF or also some additional formats? Can I assume the "compilation phase" happens on your local machine and the web application cares only about the ready deliverables?

**Comment by jackkinsella** [comment]
I am pretty sure it will be multi-format (e.g. .pdf and .mobi)

As regards the compilation phase, let's presume it happens locally for now.

**Comment by jackkinsella** [comment]
Promising compilation software: https://github.com/softcover/softcover

Built by Michael Hartl for Rails Way.
