### ISSUE TITLE
Book details page

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#25]
@jackkinsella What content do we want to present in the book details page?

Some obvious guesses are:
- title
- description (plain free text)

1. Do we need some structured fields like for instance number of pages?
2. Book cover as the image?
3. Should we make the description a little bit smarter? We could add Markdown support.
4. Do you want to offer some free PDF samples for download?

**Comment by jackkinsella** [comment]
Off the top of my head, we'll also need the following:

* faq
* author information and pic
* table of contents / chapter list
* testimonials
* share buttons
* money back guarantee (see http://www.jstorimer.com/products/working-with-unix-processes)

1 No structured fields necessary...page numbers etc. can be written about in the descriptive text.

2 Yes book cover as an image.

3 Not sure if we'll need that... let's wait and see.

4 Samples will present, but most likely as HTML, thanks to their added SEO benefit. I guess these will be sub-pages off the book page.

Check out these website for some inspiration about what a sales page would contain:

https://www.railstutorial.org/book
http://www.jstorimer.com/products/working-with-unix-processes
https://www.objc.io/books/advanced-swift/

**Comment by adamniedzielski** [comment]
I think that this one can be closed. Majority of the things mentioned is done and the rest will probably come up when we have the design.
