### ISSUE TITLE
Configure the domain to point to Heroku app

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#28]

**Comment by adamniedzielski** [comment]
@jackkinsella What will be the domain name? http://www.jackkinsella.ie/ ?

**Comment by jackkinsella** [comment]
yep, that's it. I will wait until I've moved the old content over and applied design before wiring the domain.

**Comment by jackkinsella** [comment]
I guess I want https too

**Comment by adamniedzielski** [comment]
We can have SSL for free on Heroku - https://devcenter.heroku.com/articles/ssl-beta

**Comment by jackkinsella** [comment]
brill let's have that :)
