### ISSUE TITLE
Book upgrades

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#3]
@jackkinsella What is the policy regarding updates to the books? Do customers receive updates for free? I believe that this is a pretty common approach. Or maybe we should differentiate between minor updates and major updates?

**Comment by jackkinsella** [comment]
Minor updates (e.g. fixing of typos) should be free. The file to be downloaded should just get replaced.

Major updates: don't worry about them... they are beyond the version 1 scope.
