### ISSUE TITLE
Curious about inventory management

### ISSUE THREAD

**Issue by drhenner** [jackkinsella/confessions#36]
I have a few questions.  You don't need to answer, I mostly hoping to help ask the questions you might not have asked.

1 - How will you handle inventory management?
2 - It a product has_many order_items how will you handle "variations" or the product?  I'm used to selling the product-version (like size 9 vs size 10 shoe)
3 - Do you plan for other developers to use this or just yourself?  I ask this because I see a "book" model that looks very specific to your business case.

**Comment by jackkinsella** [comment]
So I am commissioning this work for a website selling e-books, thus the lack of inventory, variations, and abstract Product models. So, yes, it will be quite specific to the digital products world.

**Comment by adamniedzielski** [comment]
The primary purpose of this application is to serve as a source of inspiration for other developers. It is not meant for a direct reuse. Later on we may extract some reusable parts out of it.
