### ISSUE TITLE
Discounts logic

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#4]
Core requirement:

"get 20% off if buy two books together"

@jackkinsella Any other discount types which you would like to have? Some ideas:

1. secret discount code which we can share with any customer (logged in or not) and they receive a percentage discount
2. global, time-limited discount for all customers ("30% off only this weekend")

**Comment by jackkinsella** [comment]
For launch, we just need the 20% off for buying two together.

But with later versions, maybe the two you mentioned.

**Comment by adamniedzielski** [comment]
@jackkinsella Is this still relevant or can we close it?
