### ISSUE TITLE
Create Sendgrid account

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#40]
@jackkinsella I believe that it makes sense to create a separate Sendgrid account (especially when it's free).

**Comment by jackkinsella** [comment]
Could we re-use our current one for the time being? I signed up for a new account on Sendgrid there but it looks like it will get rejected because we're not using a real domain name yet.

**Comment by adamniedzielski** [comment]
Sure, sounds like a good temporary solution!

**Comment by drhenner** [comment]
Did you stop working on the project or do you plan to keep it going?  I was just checking in to see the progress

**Comment by adamniedzielski** [comment]
@drhenner Thanks for your interest! We definitely plan to keep it going. The majority of the backend logic is already done (it's not very complex anyway) and we also have the e-book build toolchain in place (https://github.com/adamniedzielski/admission https://github.com/adamniedzielski/test-book).

Now we are making a pause, because I'm waiting for some designs to start working on the frontend part. In the meantime @jackkinsella is editing the book :smile:

**Comment by adamniedzielski** [comment]
@jackkinsella Can you create a new account on Sendgrid using jackkinsella.ie as the domain name?
