### ISSUE TITLE
Admin panel - authentication

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#44]
Based on the patterns how we use admin panel in Oxbridge Notes I propose to secure the admin panel just with HTTP Basic Authentication (http://api.rubyonrails.org/classes/ActionController/HttpAuthentication/Basic.html).

What do you think about it @jackkinsella?

**Comment by jackkinsella** [comment]
fine by me, esp. since the refunds will be done through Stripe
