### ISSUE TITLE
Sharing buttons from sharethis.com

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#52]
@jackkinsella Do the buttons work for you on localhost? When I click any of them I'm just redirected to a blank page.

Should we put them also on the order completed page for coherency?

**Comment by jackkinsella** [comment]
ditto, I get a blank page too... but I guess that's to expected with localhost weirdness.

On the order confirmation page, let's leave them out–I want to focus attention on the Twitter share that we already have.

**Comment by adamniedzielski** [comment]
OK, let's skip it for order confirmation page.

I've checked that it works for the article page in production. However, they add their own branding - for example Twitter share contains https://shar.es/1luiWx via @sharethis

**Comment by jackkinsella** [comment]
gah, the branding add sucks! I will look for a better solution.

**Comment by jackkinsella** [comment]
thanks for pointing it out.
