### ISSUE TITLE
Copy for our emails

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#54]
We send two emails to the customers:
- login link
- order confirmation

The copy is very basic so it needs some attention.

**Comment by jackkinsella** [comment]
@josephdb search for the login_link email file (and the order confirmation one) in the code and have a go at modifying them.

all our emails are in folders like this

app/views/xyz_mailer/

**Comment by josephdb** [comment]
(I wrote this a few hours ago but I now see you've closed the issue — thought I'd post it anyway in case you still want them tidied up/padded out)

Just getting these written up now, and I have a couple of questions:

1. "you can get in touch using the contact form or by replying to this email" <-- is this true of our auto-emails? can people get in touch by replying to them?

2. how difficult would it be to add a header image? I can throw together a simple image matching the website header v quickly just so there's something there, but I don't know how to then get it into the emails

**Comment by jackkinsella** [comment]
@josephdb These particular commits caused problems because you hadn't pulled the latest code before making the edits. I had changed the file and you edited an out-of-date version. When working with git you ought to pull the second before you start working. It's sorta annoying to remember, but that's the only way to minimise conflicts.

**Comment by josephdb** [comment]
Gah, sorry — I thought if I was editing files directly within GitHub there wouldn't be a risk of editing out of date code, but because we sort of overlapped with putting the copy in I fell behind. Will make sure I'm up to date in future.

**Comment by jackkinsella** [comment]
hmm, then we need to rethink the workflow a bit if Github doesn't update the files as I push

**Comment by josephdb** [comment]
I think it was more that I had left the page open for some time while I was making my edits, and then didn't refresh before saving? But I'm not sure, I'm a bit confused. Talk about it in our meeting tomorrow maybe?
