### ISSUE TITLE
Invoicing

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#55]

**Comment by adamniedzielski** [comment]
We will add a link to the completed order page which points to the invoice generation form. Invoice generation form will be used only by companies. Invoices for individual consumers will be handled manually, only on a special request as it's a rare case.

Invoice generation form:
- company name
- address - textarea, because we don't really care about the format here and from my experience format differs across countries
- country - dropdown, because we need this one to be precise
- VAT-ID - optional for companies outside EU

@jackkinsella 

Questions (mainly for your accountant):
1. What should be displayed in the VAT rate column for:
  a) EU companies
  b) non-EU companies

  I know that the VAT rate is 0 in both cases, but for example in Poland you cannot write 0% and you have to write "np" which stands for "nie podlega" = "does not apply". I think it's worth to ask.
2. Do we need any special notes for EU companies? In Poland I have to write "odwrócone obciążenie (reverse charge)".
3. Do we need the company name later on in the accounting reports? If not, we can merge company name and address fields for even greater flexibility.
4. How about the invoice number? We use "P-year-month-sequential_number" format (example: P2016-3-109) for Oxbridge Notes. Do we have to use exactly the same format and synchronize numbering with Oxbridge Notes? This would be extremely painful and difficult. Can we use for example "BP-year-sequential_number" format (please mind "B" letter at the beginning)?
5. You mentioned "pre-populating the form with Stripe data". Which fields would you like to pre-populate, because I cannot see any huge opportunities here?

**Comment by jackkinsella** [comment]
1. You are spot on. Just say "VAT: n/a". I.e. make it clear in the invoice that we sometimes charge VAT but didn't in this particular case.
2. Yes, we need the "reverse charge" note in Germany too. I believe it is a pan-European thing.
3. Unfortunately, yes. I would like to hang on to the company name in a separate database field just in case I need to print out something for a future audit.
4. The BP system would be perfectly fine. (As mentioned in another comment, if you can share librified code from Oxbridge Notes, then please do).
5. I just meant the customer name, address, and country.

**Comment by adamniedzielski** [comment]
5) Unfortunately the only thing which we can get by default from Stripe is the country. In order to get the customer name and address we would have to enable collecting billing address details which asks user for: billing name, address line 1, zip, state, city and country before making the payment.

I think that it doesn't make sense to ask all customers to provide these details. Moreover, pre-populating the country is probably not worth the implementation efforts, because this is just one dropdown. We will have to grab the country from Stripe anyway, but I'm not sure whether we will have this information at this point or later on.

**Comment by jackkinsella** [comment]
5. Fair enough. Let's go with your suggestions. The key piece of info we need is the country, but, as you know, that's just for the accounting report which gets created once per quarter.
