### ISSUE TITLE
Upgrade to Rails 5

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#56]
I think that we should upgrade to the latest version of Ruby and Rails before going live with the book. It's much easier and cheaper when we don't have production data to take care of.

**Comment by jackkinsella** [comment]
agreed

**Comment by adamniedzielski** [comment]
Potential issues with Carrierwave - https://github.com/carrierwaveuploader/carrierwave/issues/1991 and https://github.com/carrierwaveuploader/carrierwave/issues/1987
