### ISSUE TITLE
small kramdown issues

### ISSUE THREAD

**Issue by josephdb** [jackkinsella/confessions#60]
Here are the few problems with the kramdown we discussed last week Jack (some I've sorted already, will mark these with 👍 ):

* code snippets not looking nice like on jackkinsella.ie 👍 
* bullet points not displaying properly 👍 
* failed break at the end of 'Comprehensive Guide to Debugging Rails' 👍 
* ugly broad code snippet in 'Debugging Rails with Logs' 👍 
* URLs need to be made relative 👍 
* all URLs need double checking for 404s and replacing  👍 
* photos need adding - currently the upload fails
* numbering is squiff in the 'Debug' series 👍

**Comment by jackkinsella** [comment]
I sorted out code snippets, bullet points, failed break, ugly broad code in the latest deploy

**Comment by josephdb** [comment]
Swell, and I've sorted the numbering in the Debug series.

re: Article Photos - what should I do in the situation where the photo in the original article is broken? One in Janki is a dud : http://www.jackkinsella.ie/images/janki/bug2.png

**Comment by jackkinsella** [comment]
Just forget about lost ones

**Comment by josephdb** [comment]
Ok will do, the text surrounding the image suggests it's not vital for understanding anyway. Remaining photos are all added now, so that's everything in this issue sorted 👍
