### ISSUE TITLE
Formatting of markdown 

### ISSUE THREAD

**Issue by jackkinsella** [jackkinsella/confessions#62]
It looks like the blockquotes are too eager here... see if there is anything you can do to tame it.

https://confessions-of.herokuapp.com/articles/debugging-rails-with-pry-console

**Comment by josephdb** [comment]
All sorted I think! We have bicycles instead of blockquotes now (<3 the rockets)

**Comment by josephdb** [comment]
(leaving the issue open for any other little edits to the markdown that need doing)

**Comment by jackkinsella** [comment]
good call - I found another little one here - the Google Search Results bit is out of line somewhat /articles/debugging-rails-with-online-or-third-party-tools

**Comment by josephdb** [comment]
Ok, have merged that escaped text back into its bulletpoint. I've also put breaks between the points on this page to make it more readable, as it was a bit wall-of-text — what do you think?

**Comment by jackkinsella** [comment]
looks great, ta!

**Comment by jackkinsella** [comment]
can you add a css class to the top-bit indicating the series in all the articles that are part of the debugging series.

Here's an example:

/articles/debugging-rails-with-pry-debugger

from a markdown point of view, I just added this snippet below the paragraph about the series:

Part 3 in the series [A Comprehensive Guide To Debugging Rails](/articles/a-comprehensive-guide-to-debugging-rails)
**{: .series-highlight}**

**Comment by josephdb** [comment]
Sorted. Do we want to do anything about 'Rails' being pushed onto the next line, or are you ok with how that looks? I tried editing it to just "Part 3 *of* A Comprehensive Guide To Debugging Rails" so it fits on one line but it looked worse.

**Comment by jackkinsella** [comment]
I'm fine with it... because everyone has a different browser size, this is something we can't fully control .

**Comment by adamniedzielski** [comment]
Can we close this issue?
