### ISSUE TITLE
Watermark files

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#63]

**Comment by adamniedzielski** [comment]
Results of my research:

1) PDF - I performed initial tests and it should be easy to add a watermark at the bottom of each page using https://github.com/boazsegev/combine_pdf and https://github.com/prawnpdf/prawn This is a pure-Ruby solution (:exclamation: :exclamation: :exclamation:) so no problems with compatibility on Heroku.

2) EPUB - It's really just an archive and I was able to unpack it, modify and pack it again, and it rendered without any easy-to-spot glitches. There is a Ruby library which can help with making the changes - https://github.com/KitaitiMakoto/epub-maker#in-place-editing

3) MOBI - Unfortunately it cannot de directly edited. The suggested way is to convert to EPUB, modify and convert to MOBI. We do the conversion from EPUB to MOBI as a part of our e-book build toolchain.

The workflow may look following: Do not perform this conversion and send just PDF and EPUB to Confessions API. When a user wants to download MOBI, watermark EPUB file and convert it to MOBI on the fly. It looks like it's not that hard to get Calibre running on Heroku - https://github.com/Docverter/docverter

**Comment by adamniedzielski** [comment]
As a bonus I'm posting two links to the services which perform watermarking:
- http://biz.legimi.com/en/services/watermark/ (company from Poland 🇵🇱)
- https://www.booxtream.com/

**Comment by adamniedzielski** [comment]
Hmm... I wonder how effective the protection will be. In 3 minutes I managed to find http://www.pdfdu.com/pdf-delete-text.aspx and remove a piece of text from a PDF :disappointed:

**Comment by adamniedzielski** [comment]
Anyway, if we decide to perform the watermarking then the possible approaches are:
1. create a watermarked file on the fly, each time the user requests it
2. when order is paid, schedule a background job which performs the watermarking

I consider the second approach to be a performance optimisation, because it is more complex and requires synchronization between the browser and the background job (do not allow to download if it's not ready). I think that we should start with the first approach and see how it performs.

**Comment by jackkinsella** [comment]
so,

1. let's build our own, I want to have full control and I don't think it will be too complex.
2. don't worry the possibility of users deleting because this game is about FEAR. I will state in the book's copyright warning that we use visible and invisible watermarking that is impossible to fully remove without a degree in computational forensics.
3. I like your first approach too - on demand is A-OK by me.

**Comment by adamniedzielski** [comment]
I'm trying to get Calibre working on Heroku. I tried to install it from APT, but then I can many errors related to Python, so I guess it's not the best way.

**Comment by jackkinsella** [comment]
Failing that, the Oxbridge Notes DocServices VPS is available.

**Comment by adamniedzielski** [comment]
I managed to install Calibre on Heroku using this buildpack - https://github.com/kiskolabs/heroku-buildpack-calibre

It has two issues which I reported:
1. https://github.com/kiskolabs/heroku-buildpack-calibre/issues/2 - I made a workaround here - https://github.com/jackkinsella/confessions/commit/fde270f766dab5f4e85936af985d1c7041560d7c
2. https://github.com/kiskolabs/heroku-buildpack-calibre/issues/1 - I don't know how likely it is that Calibre breaks at some point in the future, but it would be a good practice to specify an exact version

**Comment by adamniedzielski** [comment]
Unfortunately, ```ebook-convert``` is slow and we hit 30 seconds request limit on Heroku.

This means that we would have to switch to the option 2 - "when order is paid, schedule a background job which performs the watermarking". Do you want me to spend time on this or do you prefer to leave MOBI without a watermark (`ebook-convert` is not used for PDF and EPUB)?

**Comment by jackkinsella** [comment]
dang. Let's leave .mobi aside for now.

**Comment by jackkinsella** [comment]
I can always go back and add this myself later.

**Comment by adamniedzielski** [comment]
After discussion: move watermarking to the background so we can handle MOBI as well.
