### ISSUE TITLE
Switch Heroku to real dynos

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#66]
Reminder before going live. We should upgrade dynos to prevent sleeping.

**Comment by jackkinsella** [comment]
I guess we need a web and a worker dyno, right?

**Comment by adamniedzielski** [comment]
Yes, definitely. We use Sidekiq for background jobs so we need a worker dyno.

**Comment by jackkinsella** [comment]
Sorted it out already
