### ISSUE TITLE
"But but... worries and objections" - content switcher

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#69]
I would expect the arrow to always be next to the currently displayed item. Currently it is always next to the first item.

Are you sure that the content switcher is a good idea? We could just display the content one below the other.

**Comment by jackkinsella** [comment]
The idea behind the switcher is to create visual variation. Simply having a block of text is ineffective at getting people to read it... therefore conversion optimisation experts recommend varying it up, even if it's with silly bits and pieces. e.g. check out http://conversionxl.com/how-to-design-kickass-long-form-sales-pages/

Anyway, I've fixed it up mostly, I'm still having some trouble with removing the css '.selected-objection' class on line 3, unobtrusive.coffee. Could you take a look later?

**Comment by jackkinsella** [comment]
(I'm also curious to learn what went wrong, so let me know what my mistake was.)

**Comment by adamniedzielski** [comment]
I made some bigger changes to simplify the code. I guess the main idea was to attach the click handler to the `selectable-objection` div and only add or remove `selectable-objection--selected` class from this div. This saves us from changing classes for both the link and the triangle.

**Comment by adamniedzielski** [comment]
This commit https://github.com/jackkinsella/confessions/commit/a4ed19c01fced5a9146e893510adcdb3ff9fee0a broke the arrow next to the content switcher.
