### ISSUE TITLE
Janki method rules

### ISSUE THREAD

**Issue by jackkinsella** [jackkinsella/confessions#77]
I added some custom css to allow us to recreate those coloured boxes on the original page

Here's the example markdown:

````
*The first rule of **Janki** boosts your memory:*  
**“Every time you learn something new create a question and answer flashcard and add this card to Anki.”**
{: .janki-rule}
````

The important thing to notice is that I forced a line break at the end of line 1 by putting two spaces at the end of the line. All this means is pressing space twice after the *

**Comment by jackkinsella** [comment]
original http://www.jackkinsella.ie/2011/12/05/janki-method.html

**Comment by jackkinsella** [comment]
(the other formatting is a bit weird, but I'm working on it)

**Comment by josephdb** [comment]
All sorted. Thanks for the help, couldn't for the life of my figure out how to replicate those rule boxes!

**Comment by jackkinsella** [comment]
The trick was that we needed to style the paragraph with a CSS class. What you see up there wraps the paragraph with the ".janki-rule" style which causes the border.
