### ISSUE TITLE
Coffeescript

### ISSUE THREAD

**Issue by adamniedzielski** [jackkinsella/confessions#79]
@jackkinsella I don't think that starting a project with Coffeescript is a good idea nowadays. Since the introduction of ES6, Coffeescript is in decline and it may become obsolete in a short time.

See:
- https://gitlab.com/gitlab-org/gitlab-ce/issues/20098
- http://techblog.evite.com/post/coffeescript-to-es6/

I think that it's better to use the plain JavaScript and migrate to ES6 when it's supported by the asset pipeline (without external gems which may be unstable).

**Comment by jackkinsella** [comment]
@adamniedzielski fair enough, have done. Please pull before you work on the pointer JS thing.
