### ISSUE TITLE
article photo urls need migrating

### ISSUE THREAD

**Issue by josephdb** [jackkinsella/confessions#81]
The photos in the article are based on the confessions-of url rather than jackkinsella.ie (e.g. https://confessions-production.s3.amazonaws.com/uploads/photo/file/7/anki.jpg), so I'm imagining they might break once we've moved over to the latter domain.

I tried using just relative urls for the images but they broke, so I'm making this issue to remind myself to go back and update them once we've moved house. And if they don't get broken in the move, never mind!

**Comment by adamniedzielski** [comment]
@josephdb I don't expect these links to break during the migration of our domain.

Our application is currently hosted on confessions-of.herokuapp.com domain and these images have URLs beginning with confessions-production.s3.amazonaws.com They are hosted externally, using a service called [Amazon S3](https://en.wikipedia.org/wiki/Amazon_S3) which is basically a storage space for our application.

**Comment by josephdb** [comment]
Ah, great! That makes sense. Thanks Adam :)
