### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by jackkinsella** [jackkinsella/confessions#85]
I know there are a few areas I added last minute without tests... but that ought to be ameliorated soon.

**Comment by adamniedzielski** [comment]
- [ ] updating book in the admin panel
- [ ] downloading PDF preview (with JS)
- [ ] assigning tags to article in the admin panel
- [ ] related articles

**Comment by jackkinsella** [comment]
all the  above :)

**Comment by adamniedzielski** [comment]
Unfortunately, I was not able to test downloading PDF preview with JS turned on. I encountered some weird issues with PDF file not being served by the server when JS was enabled. I created a test without JS.
