### ISSUE TITLE
Add "subscribe to mailing list" checkbox in checkout flow

### ISSUE THREAD

**Issue by jackkinsella** [jackkinsella/confessions#92]
Default should be ticked.

Want to send them emails and still remain compliant.

**Comment by jackkinsella** [comment]
Previous people who ordered should count as unsubscribed too.

**Comment by adamniedzielski** [comment]
Sidenote: we will need a single-click unsubscribe link once you begin sending these emails. Moreover, we will probably need a way to change the decision in the account settings page (which we don't have at the moment).

**Comment by adamniedzielski** [comment]
@jackkinsella I think that you can come up with a much better copy for the checkbox than I committed (I didn't spend time on it). From my own experience, a good copy can convince me to leaving the option checked, while if it's some default wording I usually uncheck the option.
